name: Security Scan

on:
  push:
    branches:
      - '*'

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit # Instala o bandit junto com as outras dependências
  

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: Run Bandit
        run: |
          bandit -r . || true 
      - name: Start Django development server
        run: |
          python manage.py migrate 
          python manage.py runserver &
        env:
          SECRET_KEY: ${{ secrets.DJANGO_PROD_SECRET_KEY }}


      - uses: actions/checkout@v3

      # O scan do ZAP agora pode se conectar ao servidor iniciado
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://127.0.0.1:8000"
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          sarif_output: zaproxy.sarif
        continue-on-error: true

      - name: Stop Django development server
        run: |
          # É crucial garantir que o servidor seja parado
          pkill -f "python manage.py runserver"